language: generic
sudo: false

matrix:
  include:
      #     1.28s  apt-add-repository
      #     5.76s  apt-get update
      #     23.08s apt-get install
      #     WALL TIME: 1 min 9 sec
      #
      # NB: For ghc 7.8 and earlier, the -dyn and -prof libraries are
      # not correctly whitelisted.
      - env: TYPE=hvr-ghc
        addons: {apt: {packages: [ ghc-7.10.3-dyn, ghc-7.10.3-prof ], sources: [ hvr-ghc ]}}

      #     4.97s   apt-get update
      #     6.25s   apt-get install
      #     0.36s   wget
      #     10.93s  tar xf
      #     2.30s   configure
      #     11.56s  make install
      #     WALL TIME: 1 min 2 sec
      - env: TYPE=download-xz
        addons: {apt: {packages: [ libgmp-dev, libgmpxx4ldbl ]}}
        cache:
            directories:
                - $HOME/usr

      #     4.92s   apt-get update
      #     6.10s   apt-get install
      #     0.70s   wget
      #     25.96s  tar xf
      #     1.78    configure
      #     13.45s  make install
      #     WALL TIME: 1 min 16 sec
      - env: TYPE=download-bz2
        addons: {apt: {packages: [ libgmp-dev, libgmpxx4ldbl ]}}
        cache:
            directories:
                - $HOME/usr

before_install: true
cache:
install:
 - VERSION="7.10.3"
 - PATCHFIX="b"
 - if [[ "$TYPE" = "download-xz" ]] && [ ! -e $HOME/usr/bin/ghc-$VERSION ]; then SUFFIX="xz"; fi
 - if [[ "$TYPE" = "download-bz2" ]] && [ ! -e $HOME/usr/bin/ghc-$VERSION ]; then SUFFIX="bz2"; fi
 - BASENAME="ghc-$VERSION$PATCHFIX-x86_64-deb7-linux.tar.$SUFFIX"
 - URL="http://downloads.haskell.org/~ghc/$VERSION/$BASENAME"
 - if [[ ! -z "$SUFFIX" ]]; then wget "$URL"; fi
 - if [[ ! -z "$SUFFIX" ]]; then tar xf "$BASENAME"; fi
 - if [[ ! -z "$SUFFIX" ]]; then cd "ghc-$VERSION"; fi
 - if [[ ! -z "$SUFFIX" ]]; then ./configure --prefix="$HOME/usr"; fi
 - if [[ ! -z "$SUFFIX" ]]; then make install; fi
 - export PATH="$HOME/usr/bin:$PATH"
 - if [[ "$TYPE" = "hvr-ghc" ]]; then export PATH="/opt/ghc/$VERSION/bin:$PATH"; fi
before_script: true
script:
 - ghc --version
 - echo "main = return ()" > Main.hs
 - ghc --make Main.hs
 - ghc --make Main.hs -prof
